version: '2'

services:
  web:
    build: .
    user: node
    working_dir: /code
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/code
      - api-deps:/code/node_modules
    ports:
      - 8080:8080
    command: "yarn start"

volumes:
  api-deps:
