version: '2'

services:
  web:
    build: .
    working_dir: /code
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/code
      - npm:/code/node_modules
    ports:
      - 8080:8080
    command: "yarn start"

volumes:
  npm:
